size: 4
ckpt_path: ./models/DQN.pt
train: False
device: cpu
learning_rate: 0.001
batch_size: 256
discount: 0.9
eps_end: 0.01
eps_start: 0.99
eps_decay: 1000
target_update: 500
num_episodes: 5000
memory_size: 10000
show_plots: True
